// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkEkfjyvuY3NfUwCrkEXW_aJKemEA6eSg',
    appId: '1:896217259852:web:c4f68af268e1739c1339e9',
    messagingSenderId: '896217259852',
    projectId: 'talaninfrability',
    authDomain: 'talaninfrability.firebaseapp.com',
    storageBucket: 'talaninfrability.appspot.com',
    measurementId: 'G-NCS7LPLC0L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkmb5vYYR9oHbfnmhbd_e49AaXA1o1AQY',
    appId: '1:896217259852:android:cd1548fe2ad89ed81339e9',
    messagingSenderId: '896217259852',
    projectId: 'talaninfrability',
    storageBucket: 'talaninfrability.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmDXUVgdfNJn2V_KdzHcMKIo9Ip-jUelI',
    appId: '1:896217259852:ios:1d1016d0d1396fdf1339e9',
    messagingSenderId: '896217259852',
    projectId: 'talaninfrability',
    storageBucket: 'talaninfrability.appspot.com',
    iosClientId: '896217259852-pjdfnffh9qdncvm80l88u03i5cu1o4eu.apps.googleusercontent.com',
    iosBundleId: 'com.example.infrability',
  );
}
